version: '3'
services:
  lampa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lampa
    ports:
      - "8080:80"
    restart: unless-stopped
    tty: true
    environment:
      - domain=${DOMAIN}
